- name: Install a .deb package from the internet.
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Add apt repos
  apt_repository:
    repo: "{{ item }}"
    codename: disco
  loop: "{{ apt_repos }}"

- name: Install a list of packages
  apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Install pip pkgs
  pip:
    name: psutil
    executable: pip3


- name: remove ubuntu gnome dock
  apt:
    name: gnome-shell-extension-ubuntu-dock
    state: absent
