---
- name: Check library dir exist
  file:
    path: "{{ playbook_dir }}/library"
    state: directory

- name: Install/update library
  get_url:
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/library/{{ item | basename }}"
  loop: "{{ local_modules_srcs }}"
