---
- name: 'Tmux : Install config file'
  get_url:
    url: https://gist.githubusercontent.com/shipilovds/1472461cf0c77dd1ef293b8ee0bf3310/raw/8e0482157cbe0fbb0a0ac56a977dde1a160498cb/tmux.conf
    dest: ~/.tmux.conf

- name: 'Tmux : Install utility for status panel'
  get_url:
    url: https://gist.githubusercontent.com/shipilovds/c58ad1e0b267bf29c1b90ade28b0171b/raw/97da93020ca9817d46aa5daa5c6da95d2e6b0f37/cpum.py
    dest: /usr/bin/cpum
    mode: u=rwx,g=rx,o=rx
  become: True
