---
- name: 'DNF : Add repos'
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: "{{ item.gpgcheck }}"
  loop: "{{ pkgs_dnf_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: 'DNF : Install packages'
  dnf:
    name: "{{ pkgs_dnf_packages }}"
