---
- name: Oh My Zsh deployment
  include: ohmyzsh.yml
  tags: ['ohmyzsh']

- name: Gnome Shell Extensions management
  include: gnome_extensions.yml
  when: env_gnome_extensions_list
  tags: ['gnome_extensions']

### TODO: Need to fix module's code.
# - include: gsettings.yml
