---
- name: 'OhMyZsh : Cloning repo as config dir'
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: "~/.oh-my-zsh"
    force: True

- name: 'OhMyZsh : Install additional plugins'
  git:
    repo: "{{ item }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.split('/')[-1].split('.')[0] }}"
  loop: "{{ env_ohmyzsh_additional_plugins }}"
  loop_control:
    label: "{{ item.split('/')[-1] }}"

- name: 'OhMyZsh : Install config file'
  template:
    src: 'zshrc.j2'
    dest: "~/.zshrc"

- name: 'OhMyZsh : Ensure user is using zsh shell'
  user:
    name: "{{ ansible_env.USER }}"
    shell: '/bin/zsh'
  become: True
